---
kind: Service
apiVersion: v1
metadata:
  name: traefik-proxy
  namespace: default
spec:
  type: NodePort
  selector:
    k8s-app: traefik-proxy
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      name: http
    - protocol: TCP
      port: 8099
      nodePort: 30099
      name: auth
